### ISSUE TITLE
Fork postcss-import

### ISSUE THREAD

**Issue by leebenson** [eriklharper/postcss-nested-import#2]
On reflection, I think it'd make more sense to fork and PR and [postcss-import](https://github.com/postcss/postcss-import) vs building a home-brew version.

postcss-import has a lot of functionality out-the-box, including duplicate detection and proper handling of paths and external resources. The only thing it's missing is an option to disable top-level `@import` checking, and concatenate in place.

It would probably make more sense to add an option for disabling top-level enforcement of imports and submit a PR than building something separate.

What do you think @eriklharper?

**Comment by leebenson** [comment]
the feature has already been suggested by one of the maintainers there, btw (https://github.com/postcss/postcss-import/issues/214#issuecomment-258257113) -- just hasn't been done yet.

**Comment by eriklharper** [comment]
I totally agree, I think its silly to reinvent the wheel of what's already been built.

**Comment by eriklharper** [comment]
@leebenson I would like to contact you directly.  Do you have a google account?  Would be great to chat with you real time

**Comment by dehuszar** [comment]
Is this refactor still planned?  I have need of this plugin as a dependency to my own, due to postcss-import's spec-strictness.

**Comment by Akimyou** [comment]
See this issue. It seems postcss-import no want to support css scoped nested import.

https://github.com/postcss/postcss-import/issues/296
