### ISSUE TITLE
Promise

### ISSUE THREAD

**Issue by hosein2398** [eriklharper/postcss-nested-import#3]
Hey,
I was just wondering that why do you return a promise in line 40?
I'm really confused, it's like no need to return a promise there, is there any specific reason that you do that ?
And in line 48 you why not to write something like this:
```js
readFile(path).then(fileContents => importAtRule.replaceWith(fileContents)));
```
Thanks

**Comment by revelt** [comment]
we've just released 0.2.0, please upgrade
