### ISSUE TITLE
An "error reading file" error was caught when importing based on the current directory

### ISSUE THREAD

**Issue by linhe0x0** [eriklharper/postcss-nested-import#7]
With the following structure, when I try to import reboot.css with `@import './reboot.css';` in app.css, an "error reading file" error was caught. For work, I have to import it with `@import './src/reboot.css';`, but it's confusing.

```
app
├── package.json
├── postcss.config.js
├── src
│   ├── app.css
│   ├── reboot.css
├── dist
```

- reproduce link: Open https://stackblitz.com/edit/node-mu6fph?file=src%2Fapp.css and run `npm run dev`

**Comment by mike-potter** [comment]
Any chance of getting this added? We really need to support including files relative to the parent css file (current directory).  We can't use absolute paths in our includes.

**Comment by revelt** [comment]
I patched the @linhe0x0 PR and raised it on https://github.com/eriklharper/postcss-nested-import/pull/15 — please help to test it — that one was carved off the latest v1.1.0 — thank you
